#
# Code generated by `gkgen`
#

.DEFAULT_GOAL := run
.PHONY: build

# Service
name := cms
version := 0.2.0

-include .makerc

lint:
	@exit 1

debug:
	@npm run debug

run:
	@npm run develop

serve:
	@npm run start

build:
	@NODE_ENV=production npm run build

helm:
	@gkgen -k $(args) .
	@helm lint chart

# K8s
oci:
	@rm app.tar || true
	@tar -cvf app.tar --exclude='node_modules' --exclude='.git'  --exclude='.cache' ./
	@buildah bud -t $(name):$(version) --build-arg name=$(name) --build-arg version=$(version)

ifneq ($(and $(REGISTRY_USERNAME),$(REGISTRY_PWD)),)
	@buildah login -u $(REGISTRY_USERNAME) -p $(REGISTRY_PWD) $(REGISTRY)
	buildah push $(name):$(version) $(REGISTRY)/$(REGISTRY_REPO)/$(name):$(version)
endif

# Helm chart
package:
	@helm cm-push chart/ hub-dev

deploy: package
	@ssh $(SSH_DESTINATION) '$(HELM_CMD) install $(name) hub-dev/$(name) -n dev'

deploy-delete: package
	@ssh $(SSH_DESTINATION) '$(HELM_CMD) uninstall $(name) hub-dev/$(name) -n dev'

deploy-restart:
	@ssh $(SSH_DESTINATION) '$(KUBECTL_CMD) rollout -n dev restart deploy/$(name)'

package-prod:
	@helm cm-push chart/ hub

deploy-prod: package-prod
	$(HELM_CMD) install $(name) hub-dev/$(name) -n prod
