#
# Code generated by `gkgen`
#

.PHONY: build

# Environments
-include .makerc

define get_base_config
$(shell perl -nle 'print $$1 if /$1/' .config/service.base.yaml)
endef

define get_k8s_config
$(shell perl -nle 'print lc $$1 if /$1/' .config/service.k8s.yaml)
endef

# Service
NAME			= $(call get_base_config,name: (\S+))
VERSION			= $(call get_base_config,version: (\S+))
DESCRIPTION		= $(call get_base_config,description: (.+))
README			= $(call get_base_config,readme: (\S+))
NAMESPACE		?= $(call get_base_config,namespace: (\S+))

# Registry
REGISTRY 		?= registry.gitlab.com
REGISTRY_REPO 	?= free-mind/hub
DOCKERFILE 		?= Dockerfile
DEPLOYMENT_KIND	?= $(call get_k8s_config,kind: (\w+))

ifeq ($(HELM_NAMESPACE),)
ifneq ($(NAMESPACE),)
	HELM_NAMESPACE	= $(NAMESPACE)
else
	HELM_NAMESPACE	= dev
endif
endif

# OCI
ifndef IMAGE
	ifneq ($(NAMESPACE),)
		IMAGE	= $(NAMESPACE)-$(NAME)
	else
		IMAGE	= $(NAME)
	endif
endif

TAG				?= $(VERSION)

# Lists all targets
help:
	@grep -B1 -E "^[a-zA-Z0-9_%-]+\:([^\=]|$$)" Makefile \
		| grep -v -- -- \
		| sed 'N;s/\n/###/' \
		| sed -n 's/^#: \(.*\)###\(.*\):.*/\2###\1/p' \
		| column -t -s '###'

#: Removes untracked files from the working tree
clean:
#	go clean -cache -testcache -modcache -x
	gkgen clean $(arg)

#: Apply patches
patch-update:
	@npm run patch-update

#: Creates patches
patch:
	@npm run patch

#: Linting
lint:
	@npm run lint

#: Starts the application with autoReload enabled
run:
	@npm run develop

#: Starts the application with autoReload disabled
serve:
	@npm run start

#: Builds the admin panel
build:
	@NODE_ENV=production npm run build

# -----------------------------------------------------------------------------
# OCI
# -----------------------------------------------------------------------------
#: Builds an OCI image using instructions in 'Dockerfile'
oci:
	podman build -t $(IMAGE):$(VERSION) -f $(DOCKERFILE) $(args) \
		--annotation org.opencontainers.image.created="$(shell date -I'seconds')" \
		--annotation org.opencontainers.image.description="$(DESCRIPTION)" \
		--annotation io.artifacthub.package.readme-url="$(README)"

#: Pushes an image to a specified location that defined in '.makerc'
oci-push:
	podman login $(REGISTRY)
	podman push $(IMAGE):$(VERSION) $(REGISTRY)/$(REGISTRY_REPO)/$(IMAGE):$(TAG)

# -----------------------------------------------------------------------------
# Helm
# -----------------------------------------------------------------------------
#: Generates the Helm chart
helm:
	gkgen helm $(args)
	cp .config/service.k8s.yaml .chart/values.yaml
ifneq ($(wildcard .chart/Chart.lock),)
	rm .chart/Chart.lock
endif
	helm dependency build .chart/
	helm lint .chart/

#: Render chart templates locally and write to '.chart/k8s.yaml'
pod: helm
	helm template $(IMAGE) .chart/ > .chart/k8s.yaml

#: Uploads chart to the repo that defined in '.makerc'
package: helm
	helm cm-push .chart/ $(HELM_REPO)

#: Installs the chart to a remote defined in '.makerc'
install:
	helm repo update && helm install $(IMAGE) $(HELM_REPO)/$(IMAGE) -n $(HELM_NAMESPACE) --version $(VERSION) $(args)

#: Upgrades the release to the current version of the chart
upgrade:
	helm repo update && helm upgrade $(IMAGE) $(HELM_REPO)/$(IMAGE) -n $(HELM_NAMESPACE) --version $(VERSION) $(args)

#: Restarts the release
restart:
	kubectl rollout restart $(DEPLOYMENT_KIND)/$(IMAGE) -n $(HELM_NAMESPACE) $(args)

#: Uninstalls the service
uninstall:
	helm uninstall $(IMAGE) -n $(HELM_NAMESPACE) $(args)
